INSERT INTO lecture (created_at, updated_at, title) VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '신나는 JPA 특강');

INSERT INTO lecture (created_at, updated_at, title) VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '신나는 MySQL 특강');

INSERT INTO lecture_schedule (REGISTER_COUNT, REGISTER_MAX_COUNT, CREATED_AT, LECTURE_DATE_TIME, LECTURE_ID, UPDATED_AT, SPEAKER) VALUES
    (0, 30, CURRENT_TIMESTAMP, TIMESTAMP '2024-10-12 11:00:00', 1, null, '제강연');

INSERT INTO lecture_schedule (REGISTER_COUNT, REGISTER_MAX_COUNT, CREATED_AT, LECTURE_DATE_TIME, LECTURE_ID, UPDATED_AT, SPEAKER) VALUES
    (0, 30, CURRENT_TIMESTAMP, TIMESTAMP '2024-10-12 12:00:00', 1, null, '제강연');

INSERT INTO lecture_schedule (REGISTER_COUNT, REGISTER_MAX_COUNT, CREATED_AT, LECTURE_DATE_TIME, LECTURE_ID, UPDATED_AT, SPEAKER) VALUES
    (0, 30, CURRENT_TIMESTAMP, TIMESTAMP '2024-10-19 12:00:00', 1, null, '제강연');

INSERT INTO lecture_schedule (REGISTER_COUNT, REGISTER_MAX_COUNT, CREATED_AT, LECTURE_DATE_TIME, LECTURE_ID, UPDATED_AT, SPEAKER) VALUES
    (0, 30, CURRENT_TIMESTAMP, TIMESTAMP '2024-10-12 11:00:00', 2, null, '마강연');
